name: yaw_phonenumber_platform_interface
description: Yet another wrapper for libphonenumber (Platform interface).
version: 0.0.1
author: Ilya Yachin

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^1.1.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter